# Generated by Django 3.1.3 on 2020-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='zip',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
    ]
