# Generated by Django 3.1.3 on 2020-11-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0003_auto_20201115_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='', upload_to='clients/images/'),
        ),
    ]
