# Generated by Django 3.1.3 on 2020-11-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0004_auto_20201116_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to='clients/images/'),
        ),
    ]
