# Generated by Django 3.1.3 on 2020-11-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0006_auto_20201116_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
