# Generated by Django 3.1.3 on 2020-11-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='type',
            field=models.CharField(choices=[('Indian', 'Indian'), ('American', 'American'), ('Chinese', 'Chinese'), ('Italian', 'Italian')], default='Please Choose a Type', max_length=20),
        ),
    ]
