# Generated by Django 3.1.3 on 2020-11-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dish', '0005_auto_20201117_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='image',
            field=models.FileField(upload_to='dishes/images/'),
        ),
    ]
