# Generated by Django 3.1.3 on 2020-11-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dish', '0007_auto_20201117_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindish',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
