# Generated by Django 3.1.3 on 2020-11-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dish', '0009_auto_20201117_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindish',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
