# Generated by Django 3.1.3 on 2020-11-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cust', '0009_remove_client_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.client')),
            ],
        ),
    ]
