# Generated by Django 3.1.3 on 2020-11-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0002_revieworder_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='revieworder',
            name='rating',
            field=models.CharField(choices=[('Bad', 'Bad'), ('Good', 'Good'), ('Average', 'Average'), ('Worst', 'Worst'), ('Excellent', 'Excellent'), ('Unmatchable', 'Unmatchable')], default='Good', max_length=15),
        ),
    ]
