# Generated by Django 3.1.3 on 2020-11-25 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0007_auto_20201125_1004'),
        ('Order', '0002_auto_20201124_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.client'),
        ),
    ]
