# Generated by Django 3.1.3 on 2020-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_time',
            field=models.DateField(auto_now=True),
        ),
    ]
