# Generated by Django 3.1.3 on 2020-11-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_order_placed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
