# Generated by Django 3.1.3 on 2020-11-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_auto_20201126_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_datetime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
