# Generated by Django 3.1.3 on 2020-11-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_order_delivery_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_datetime',
        ),
    ]
